# 23-3. Tensorflow2 API로 모델 작성하기: MNIST (1) Sequential API 활용

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
mnist = keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0
print(x_train[0])

x_train = x_train[...,np.newaxis] #... 기호는 : 기호와 같다. 
x_test = x_test[...,np.newaxis] #np.newaxis를 해주면 한 축이 더 생긴다. 

print(len(x_train),len(x_test))
print(x_train)
print(x_test)


60000 10000
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [

In [5]:
model = keras.Sequential([
    tf.keras.layers.Conv2D(32,3,activation='relu'),
    tf.keras.layers.Conv2D(64,3,activation='relu'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10,activation='softmax')
])

In [6]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train,y_train,epochs=5)
model.evaluate(x_test,y_test,verbose=2)

2023-01-09 10:38:18.797991: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-09 10:38:18.798297: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 249s 4ms/sample - loss: 0.1081 - accuracy: 0.9671
Epoch 2/5
60000/60000 [==============================] - 231s 4ms/sample - loss: 0.0352 - accuracy: 0.9891
Epoch 3/5
60000/60000 [==============================] - 237s 4ms/sample - loss: 0.0181 - accuracy: 0.9941
Epoch 4/5
60000/60000 [==============================] - 234s 4ms/sample - loss: 0.0133 - accuracy: 0.9956
Epoch 5/5
60000/60000 [==============================] - 243s 4ms/sample - loss: 0.0090 - accuracy: 0.9971
10000/1 - 11s - loss: 0.0295 - accuracy: 0.9861


[0.058468574920261425, 0.9861]

# 23-4. Tensorflow2 API로 모델 작성하기: MNIST (2) Functional API 활용

In [7]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [8]:
mnist = keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

x_train = x_train[...,np.newaxis]
x_test = x_test[...,np.newaxis]

print(len(x_train),len(x_test))

60000 10000


In [ ]:
inputs = keras.Input(shape=(28,28,1))
x = keras.layers.Conv2D(32,3,activation='relu')(inputs)
x = keras.layers.Conv2D(64,3,activation='relu')(x)
x = keras.layers.Flatten()(x)
x = keras.layers.Dense(128,activation='relu')(x)
predictions = keras.layers.Dense(10,activation='softmax')(x)

model = keras.Model(inputs=inputs,outputs = predictions)

In [11]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train,y_train,epochs=1)
model.evaluate(x_test,y_test,verbose=2)

Train on 60000 samples
60000/60000 [==============================] - 309s 5ms/sample - loss: 0.0083 - accuracy: 0.9975
10000/1 - 10s - loss: 0.0234 - accuracy: 0.9885


[0.04677463309699412, 0.9885]

# 23-5. Tensorflow2 API로 모델 작성하기: MNIST (3) Subclassing 활용

In [12]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [13]:
mnist = keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train = x_train/255.0
x_test = x_test / 255.0

x_train = x_train[...,np.newaxis]
x_test = x_test[...,np.newaxis]

In [14]:
class MyModel(keras.Model):
    def __init__(self):
        super(MyModel,self).__init__()
        self.conv1 = keras.layers.Conv2D(32,3,activation='relu')
        self.conv2 = keras.layers.Conv2D(64,3,activation='relu')
        self.flatten = keras.layers.Flatten()
        self.dense1 = keras.layers.Dense(128,activation='relu')
        self.dense2 = keras.layers.Dense(10,activation='softmax')
    
    def call(self,x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.flatten(x)
        x = self.dense1(x)
        return self.dense2(x)
    
model = MyModel()

In [15]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])
model.fit(x_train,y_train,epochs=1)
model.evaluate(x_test,y_test,verbose=2)

Train on 60000 samples
60000/60000 [==============================] - 225s 4ms/sample - loss: 0.1058 - accuracy: 0.9670
10000/1 - 10s - loss: 0.0488 - accuracy: 0.9820


[0.0507754402782768, 0.982]